apiVersion: v1
kind: Service
metadata:
  name: rag-external
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    run: rag-manual
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rag-external
subsets:
- addresses:
  - ip: 172.40.0.206
  ports:
  - port: 8000
    protocol: TCP
