apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rag
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-rag
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-rag
  nfs:
    server: 172.40.0.63
    path: /data/nfs/rag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-rag
  resources:
    requests:
      storage: 20Gi
